image: gradle:6.3.0-jre14

stages:
  - test
  - build

java:
  stage: test
  script:
    - gradle test
  only: 
    - merge_requests

image: docker:latest

services:
  - docker:dind
  
variables:
  DOCKER_HOST: tcp://localhost:2375

build:
  stage: build
  script:
    - docker build -t test .
