image: gradle:6.3.0-jre14

stages:
  - test
  - build

java:
  stage: test
  script:
    - gradle test
  only: 
    - merge_requests

image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:8093


build:
  services:
   - docker:18.09-dind
  stage: build
  script:
    - docker build -t test .
