image: gradle:6.3.0-jre14

stages:
  - test
  - build

java:
  stage: test
  script:
    - gradle test
  only: 
    - merge_requests

image: docker:19.03.12

build:
  stage: build
  services:
   - docker:19.03.12-dind
  script:
    - docker build -t test .
